---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: latency

resources:
- ../../base
- ingress.yaml

images:
- name: latency
  newName: localhost:5001/latency
  newTag: latest
